version: '2'
services:

  proxy:
    network_mode: bridge
    image: nginx:latest
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - './logs:/etc/nginx/logs'
      - './devcerts:/etc/nginx/certs'
    ports:
      - '443:443'
      - '80:80'