version: '2'
services:

  proxy:
    network_mode: bridge
    image: nginx:latest
    environment:
      # requests will be forwarded to http://<DOCKER_HOST>:<TARGET_PORT>
      # This will be similar to accessing: http://localhost:8080
      - TARGET_PORT=8080
    volumes:
      - './nginx-default.conf.template:/etc/nginx/templates/default.conf.template'
      - './devcerts:/etc/nginx/certs'
    ports:
      - '443:443'
      - '80:80'
